import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { wagmiConfig } from "@/config/wagmi";
import { cookieToInitialState } from "wagmi";
import { headers } from "next/headers";
import WagmiProvider from "@/providers/WagmiProvider";
import {
  MutationCache,
  QueryClient,
  QueryClientProvider,
} from "@tanstack/react-query";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    wagmiConfig,
    headers().get("cookie")
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiProvider initialState={initialState}>{children}</WagmiProvider>
      </body>
    </html>
  );
}
